### ISSUE TITLE
VideoOverlay Example not working

### ISSUE THREAD

**Issue by Raj123456788** [ttustonic/GStreamerSharpSamples#3]
Hello,
I am trying to play a video using videooverlay and it exits the application OnOpenClick(object sender, EventArgs e) without playing the video. Can you please tell me the fix or fix it? Also, I am having issue of video shifted towards right. I am using appsink can you please point me as to how can I fix this?
![tempsnip](https://user-images.githubusercontent.com/16295521/90044656-cc51e600-dc82-11ea-8b03-2f8d0f25e5de.png)

**Comment by ttustonic** [comment]
Hello
I don't know what's the problem.
I just tried Winforms and WPF video overlay samples and they both work fine with x86 version 1.14.5

![formsoverlay](https://user-images.githubusercontent.com/5532089/90063339-81b78480-dce9-11ea-9c78-0c5e697c2771.jpg)
![wpfoverlay](https://user-images.githubusercontent.com/5532089/90063307-719fa500-dce9-11ea-9b8a-523fd4d75f01.jpg)

**Comment by Raj123456788** [comment]
had to add this line  _playbin.SetState(Gst.State.Playing); and set the timeout to a higher number. Thanks!

**Comment by Raj123456788** [comment]
Question: Why do we need to Gst.Buffer.Map(out map, MapFlags.Read) to get the dataptr? why it cannot be directly derived from the buffer?

**Comment by ttustonic** [comment]
I'm not an author of GStreamer sharp, so I can't give you proper answer.
But, since the most of the GStreamer C# bindings are automatically generated,  I guess it's the way the code generator works.
However, you should direct the questions about GStreamer and GStreamer sharp internals to the source repository (https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp) or some of the mailing lists (https://gstreamer.freedesktop.org/lists/)

**Comment by Raj123456788** [comment]
Sorry to keep bugging you. I am trying to run the WebrtcSendrcv.cs example. It keeps complaining about peerid what is criteria for peerid? I gave a bogus one and it is not working. Please tell me as I want to run this example. Also, what are we expecting from this example or how can I test it? There is no error and application crashes. can you please run it at your end and see if it works? I have confirmed installation of webrtcbin. Here is what I get 
![image](https://user-images.githubusercontent.com/16295521/90284128-4ff80800-de26-11ea-914f-8c6f48c071d2.png)

**Comment by Raj123456788** [comment]
I tried const string SERVER = "wss://webrtc.nirbheek.in:8443"; and set peerid=6136 it is throwing me an error"ERROR peer '6316' not found". Waiting for your answer. Thanks!

**Comment by ttustonic** [comment]
Please open a new issue and I'll answer there.

**Comment by ttustonic** [comment]
Please open a new issue
